export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_ALL_EXPENSES = 'GET_ALL_EXPENSES';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';

export const EDIT_EXPENSE_NAME = 'EDIT_EXPENSE_NAME';
export const EDIT_EXPENSE_PRICE = 'EDIT_EXPENSE_PRICE';
export const EDIT_EXPENSE_CATEGORY = 'EDIT_EXPENSE_CATEGORY';
export const EDIT_EXPENSE_PAIDTO = 'EDIT_EXPENSE_PAIDTO';
export const EDIT_EXPENSE_DATE = 'EDIT_EXPENSE_DATE';

// export const SET_CALENDAR = 'SET_CALENDAR';
